# Ollama
quarkus.rest-client.ollama-api.url=http://localhost:11434
quarkus.rest-client.ollama-api.scope=jakarta.inject.Singleton
quarkus.rest-client.ollama-api.read-timeout=120000
quarkus.rest-client.ollama-api.connect-timeout=5000

# Retsinformation
quarkus.rest-client.retsinformation-api.url=https://api.retsinformation.dk
quarkus.rest-client.retsinformation-api.read-timeout=30000
quarkus.rest-client.retsinformation-api.connect-timeout=5000