# Ollama REST client
quarkus.rest-client."dk.hansen.ollama.OllamaClient".url=http://localhost:11434
quarkus.rest-client."dk.hansen.ollama.OllamaClient".scope=jakarta.inject.Singleton
quarkus.rest-client."dk.hansen.ollama.OllamaClient".read-timeout=120000
quarkus.rest-client."dk.hansen.ollama.OllamaClient".connect-timeout=5000